spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.200.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

wechat:
  # 公众账号, 授权
  mpAppId: wx2c0c53987e1cad7c
  mpAppSecret: ab3d495d7aa00601ae77afc57391c44e

  # 开放平台,  卖家扫码登录用
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

#  # 支付/商户号
#  mchId: 1483469312
#  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 发起支付不需要证书, 退款需要
  keyPath:
  notifyUrl: http://cxx.nat300.top/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ


server:
  servlet:
    context-path: /sell